### ISSUE TITLE
编译固件出现dockerman错误

### ISSUE THREAD

**Issue by wqzxhpx** [garypang13/openwrt-packages#3]
你好大神，编译固件，dockerman提示错误，请问怎么解决，谢谢
![211822npm1m3kpll3ivv1p](https://user-images.githubusercontent.com/32302128/106343760-f4d9a500-62e1-11eb-89fe-5e2cdb04e1d6.png)

**Comment by garypang13** [comment]
已修复.

**Comment by wqzxhpx** [comment]
thank you

**Comment by wqzxhpx** [comment]
你好大神，用的lean的源码，feeds.conf.default添加src-git garypang13 https://github.com/garypang13/openwrt-packages还是显示错误，请大神指正，谢谢

**Comment by garypang13** [comment]
需要错误日志截图.
