### ISSUE TITLE
大神你好，我重新设置的虚拟机，用lean源码添加大神的openwrt-packages后显示bypass错误

### ISSUE THREAD

**Issue by wqzxhpx** [garypang13/openwrt-packages#4]
![微信图片_20210202091054](https://user-images.githubusercontent.com/32302128/106538173-cc96b400-6536-11eb-9bb3-debf87e4ab88.png)
如图所示，怎样才能成功编译，谢谢

**Comment by garypang13** [comment]
编译前执行这两行命令

```
sed -i 's/shadowsocksr-libev-alt/shadowsocksr-libev-ssr-redir/g' package/*/*/Makefile
sed -i 's/shadowsocksr-libev-server/shadowsocksr-libev-ssr-server/g' package/*/*/Makefile
```

**Comment by wqzxhpx** [comment]
好的大神，回家就去试试

发自我的iPhone

**Comment by wqzxhpx** [comment]
按您的操作后，又显示这个，还得麻烦大神

发自我的iPhone

**Comment by wqzxhpx** [comment]
大神，还是出现这个
![捕获](https://user-images.githubusercontent.com/32302128/106677208-4f7d4480-65f3-11eb-9108-806273708b2a.PNG)

**Comment by garypang13** [comment]
lean等源码编译本插件前请先执行
```
find package/*/ feeds/*/ -maxdepth 2 -path "*luci-app-bypass/Makefile" | xargs -i sed -i 's/shadowsocksr-libev-ssr-redir/shadowsocksr-libev-alt/g' {}
find package/*/ feeds/*/ -maxdepth 2 -path "*luci-app-bypass/Makefile" | xargs -i sed -i 's/shadowsocksr-libev-ssr-server/shadowsocksr-libev-server/g' {}
```

**Comment by wqzxhpx** [comment]
> lean等源码编译本插件前请先执行
> 
> ```
> find package/*/ feeds/*/ -maxdepth 2 -path "*luci-app-bypass/Makefile" | xargs -i sed -i 's/shadowsocksr-libev-ssr-redir/shadowsocksr-libev-alt/g' {}
> find package/*/ feeds/*/ -maxdepth 2 -path "*luci-app-bypass/Makefile" | xargs -i sed -i 's/shadowsocksr-libev-ssr-server/shadowsocksr-libev-server/g' {}
> ```

我在重新安装虚拟机用lean源码试一下，想把ssr plus+、bypass、openclash、clash、passwall、vssr都编译进固件，谢谢大神

**Comment by wqzxhpx** [comment]
> lean等源码编译本插件前请先执行
> 
> ```
> find package/*/ feeds/*/ -maxdepth 2 -path "*luci-app-bypass/Makefile" | xargs -i sed -i 's/shadowsocksr-libev-ssr-redir/shadowsocksr-libev-alt/g' {}
> find package/*/ feeds/*/ -maxdepth 2 -path "*luci-app-bypass/Makefile" | xargs -i sed -i 's/shadowsocksr-libev-ssr-server/shadowsocksr-libev-server/g' {}
> ```

在feed.conf.default里添加src-git garypang13 https://github.com/garypang13/openwrt-package后编译还是出现莫名其妙错误

**Comment by wqzxhpx** [comment]
> lean等源码编译本插件前请先执行
> 
> ```
> find package/*/ feeds/*/ -maxdepth 2 -path "*luci-app-bypass/Makefile" | xargs -i sed -i 's/shadowsocksr-libev-ssr-redir/shadowsocksr-libev-alt/g' {}
> find package/*/ feeds/*/ -maxdepth 2 -path "*luci-app-bypass/Makefile" | xargs -i sed -i 's/shadowsocksr-libev-ssr-server/shadowsocksr-libev-server/g' {}
> ```

你好大神，已经成功了，十分感谢
